Separate plugin and server, rework API (to v3)
InfernalSuite/AdvancedSlimePaper pull request #113
Opened 2024-06-01 17:38 UTC by kyngs

This PR attempts to decouple the plugin from the server.
The API has been reworked to make it simpler. The loaders have been put into a separate module the developers can depend on, or provide their own.

TO-DO:
- review
- set up the loaders module publishing
- properly document (see #109)
- wait for 1.21

2024-06-15 11:23 UTC, Paul19988 requested changes

2024-06-15 11:23 UTC, Paul19988 commented on api/src/main/java/com/infernalsuite/aswm/api/AdvancedSlimePaper.java
Could name this file "AdvancedSlimePaperAPI" just to be slightly more clear

2024-06-15 11:23 UTC, Paul19988 commented on core/src/main/java/com/infernalsuite/aswm/skeleton/SkeletonCloning.java
> +                loader == null,
Are we intending on no longer providing a way to have the world be read-only?

2024-06-16 12:51 UTC, Farmeurimmo commented on core/src/main/java/com/infernalsuite/aswm/skeleton/SkeletonCloning.java
> +                loader == null,
Please don't, read-only world are perfect when you need a same spawn on every server without the need to save or edit it.

2024-06-17 18:11 UTC, kyngs commented on core/src/main/java/com/infernalsuite/aswm/skeleton/SkeletonCloning.java
> +                loader == null,
Good catch! This was an oversight on my side

2024-06-28 14:11 UTC, Paul19988 approved these changes

2024-06-29 18:35 UTC, merged