replace ChunkPos with long
InfernalSuite/AdvancedSlimePaper pull request #119
Opened 2024-06-16 01:20 UTC by RealBauHD

This PR replaces the chunk position object with a long, as you can see in the benchmark results below, it makes adding and getting of chunks more performant, and there are fewer objects in the heap, which also reduces the load on the GC.

> Benchmark                       Mode  Cnt        Score       Error  Units
> ChunkPosAdd.chunkPosLong       thrpt    5   376826,486 ± 13855,153  ops/s
> ChunkPosAdd.chunkPosObject     thrpt    5   187344,894 ± 12827,890  ops/s
> ChunkPosGet.chunkPosLong       thrpt    5  1053721,893 ± 75300,163  ops/s
> ChunkPosGet.chunkPosObject     thrpt    5   852351,543 ± 77379,401  ops/s
> ChunkPosRemove.chunkPosLong    thrpt    5  2114315,680 ± 96877,805  ops/s
> ChunkPosRemove.chunkPosObject  thrpt    5  4645570,885 ± 46174,424  ops/s
>

2024-06-29 18:35 UTC, kyngs commented
Thanks for your PR!
This looks like a nice resource save. Can you please rebase this onto dev/1.21.0?

2024-06-29 19:55 UTC, RealBauHD commented
> Thanks for your PR! This looks like a nice resource save. Can you please rebase this onto dev/1.21.0?

Yes of course I can do that, what would be the best way to accomplish that?

2024-06-29 19:58 UTC, kyngs commented
See the paper contributor guide: https://github.com/PaperMC/Paper/blob/master/CONTRIBUTING.md as a reference on how to rebase PRs

2024-06-29 21:34 UTC, RealBauHD commented
should be ready

2024-07-02 18:46 UTC, kyngs requested changes
LGTM except the small cosmetic issue.

2024-07-02 18:46 UTC, kyngs commented on patches/server/0014-replace-ChunkPos-with-long.patch
> ++        return new SkeletonSlimeWorld(worldName, loader, readOnly, new it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap<>(0), new CompoundTag("", new CompoundMap()), propertyMap, BRIDGE_INSTANCE.g
Why the fully qualified name here?
Can you change it to an import?

2024-07-02 20:28 UTC, RealBauHD commented on patches/server/0014-replace-ChunkPos-with-long.patch
> ++        return new SkeletonSlimeWorld(worldName, loader, readOnly, new it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap<>(0), new CompoundTag("", new CompoundMap()), propertyMap, BRIDGE_INSTANCE.g
Was to keep the diff small, but shure

2024-07-08 22:53 UTC, merged

2024-07-08 22:53 UTC, kyngs commented
Thanks for your contribution!