Speed up world loading by 100%
InfernalSuite/AdvancedSlimePaper pull request #122
Opened 2024-07-25 10:05 UTC by jtJava

Meant to fix #110 
Testing was done with a small 100x100x64 world, cloning done on main thread but pretty sure it can be offloaded.

Results: 2177 ms -> 1294 ms

Before: 
https://spark.lucko.me/46jHRGoWHt
https://mclo.gs/eZfDIFC

After:
https://spark.lucko.me/DspcQn4jQL
https://mclo.gs/eDOs3Jc

Testing code: 
![image](https://github.com/user-attachments/assets/86cf9228-bb07-4f25-8a28-59efca06b586)

2024-07-25 13:53 UTC, RealBauHD requested changes
A better name on how the speed up was made like "reuse config" etc. would be nice

2024-07-25 13:53 UTC, RealBauHD commented on patches/server/0016-Speed-up-world-loading.patch
> ++                        return levelIterator.next().paperConfig();
I am not a fan of this solution, I think instead of reusing a random config from another world, we should cache a brand new with the default values or establish a new file with default values for slime worlds.

2024-07-25 13:53 UTC, RealBauHD commented on patches/server/0016-Speed-up-world-loading.patch
> ++//            SpigotConfig.config.save( SpigotConfig.CONFIG_FILE );
Completely remove the function of config saving could lead to issues and is not the right solution to deal with this.

2024-07-25 15:28 UTC, kyngs commented
Adding to the comments above, this behavior should be configurable using SlimeProperties; I can imagine use-cases where this is inappropriate.

Just a thought: couldn't we cache a "preset" config and clone it each time (so that you can still edit the config per-world), or is deep cloning of the configs not viable?

2024-07-25 15:30 UTC, kyngs commented on patches/server/0016-Speed-up-world-loading.patch
> ++//            SpigotConfig.config.save( SpigotConfig.CONFIG_FILE );
Won't this also stop other worlds from saving configs?

2024-07-25 20:01 UTC, RealBauHD commented on patches/server/0016-Speed-up-world-loading.patch
> ++//            SpigotConfig.config.save( SpigotConfig.CONFIG_FILE );
Not only the world configs, but also the normal spigot config

2024-07-26 04:20 UTC, jtJava commented on patches/server/0016-Speed-up-world-loading.patch
> ++                        return levelIterator.next().paperConfig();
You're right, I'm not sure where to cache the config files, or if they could even be generated outside of the constructor.

2024-07-26 04:21 UTC, jtJava commented
> Adding to the comments above, this behavior should be configurable using SlimeProperties; I can imagine use-cases where this is inappropriate.
> 
> Just a thought: couldn't we cache a "preset" config and clone it each time (so that you can still edit the config per-world), or is deep cloning of the configs not viable?

I added a new SlimeProperty, I agree with you that a config should be cached, and ideally grabbed whenever a world is cloned. Not sure where to start on this part though, but I did move the patch to a slightly better location.

2024-08-19 10:48 UTC, kyngs requested changes
I'm sorry, but this is kinda a mess. ASP is full of scuffed hacks, but this is possibly too much. I guess I can implement it "properly" if you won't.

2024-08-19 10:48 UTC, kyngs commented on patches/server/0016-Speed-up-world-loading.patch
> ++        if (tag.isEmpty()) {
Why apply the caching only for non-cloned worlds? I think we should do this for cloned worlds too. What's the reasoning behind this?

2024-08-19 10:48 UTC, kyngs commented on patches/server/0016-Speed-up-world-loading.patch
> ++            AdvancedSlimePaper.instance().getCachedSpigotConfigs().put(slimeWorld.getName(), server.spigotConfig);
I'm afraid this actually doesn't clone the configs -> if one were to edit the config for a single world, it would get applied to all.

2024-08-19 10:48 UTC, kyngs commented on patches/server/0016-Speed-up-world-loading.patch
> ++            }
The cloned worlds should have a separate independent (cloned) config from the original ones. This also doesn't solve the original issue -> we're still generating a new config for each (new) slime world.

2024-08-19 11:26 UTC, jtJava commented
> I'm sorry, but this is kinda a mess. ASP is full of scuffed hacks, but this is possibly too much. I guess I can implement it "properly" if you won't.

I’m not actually done yet, give me another week or two and if it’s not up to par then you can properly do it on your own timeframe

2025-03-15 16:57 UTC, closed without merging

2025-03-15 16:57 UTC, davidmayr commented
This has been implemented differently in the newest 1.21.4 builds from the development branch