Expose APIs for manual serialization/deserialization
InfernalSuite/AdvancedSlimePaper pull request #80
Opened 2023-10-18 10:30 UTC by Unoqwy

* Adds a new interface `ActiveSlimeWorld` that represents a live world, from which a snapshot can be taken at any time
* Make `loadWorld` return an `ActiveSlimeWorld` to easily get the bound bukkit world
* Adds a `SlimeFormatAdapter` interface for manual (de)serialization of slime worlds. The plugin provides a default implementation that calls the existing, unchanged, internal slime serializer.

2023-10-25 17:00 UTC, ComputerNerd100 commented
I'm gonna keep this PR open for now and review it a bit more in depth later this week, however at first glance I don't think this is something we are likely to merge in soon as the functionality added here is something we're targeting in IWM and may be out of scope for ASPaper at the moment, but I'll dig into it more and have a think

2025-03-21 14:59 UTC, davidmayr requested changes
In general, I'm not against the idea of exposing this API as users can already use an API like this by building a hacky custom slime loader with a callback or smth, so why not implement it properly.

 It would require some changes and updates to the newest ASP version on the "develop" branch (please change the merge target to develop as well). If you are no longer interested in working on this since it has been a while since this was opened, please let me know.

2025-03-21 14:59 UTC, davidmayr commented on api/src/main/java/com/infernalsuite/aswm/api/SlimePlugin.java
> +    ActiveSlimeWorld getActiveWorld(@NotNull World bukkitWorld);
Not necessary with the new SlimeWorldInstance API

2025-03-21 14:59 UTC, davidmayr commented on api/src/main/java/com/infernalsuite/aswm/api/SlimePlugin.java
> +    SlimeWorld createUnboundEmptyWorld(@NotNull String worldName, @NotNull SlimePropertyMap propertyMap);
Not necessary as the loader can be null in the normal createEmptyWorld method

2025-03-21 14:59 UTC, davidmayr commented on api/src/main/java/com/infernalsuite/aswm/api/world/ActiveSlimeWorld.java
> +public interface ActiveSlimeWorld extends SlimeWorld {
Not necessary with the new SlimeWorldInstance API

2025-03-21 14:59 UTC, davidmayr commented on core/src/main/java/com/infernalsuite/aswm/serialization/slime/DefaultSlimeFormatAdapter.java
> +    private final @Nullable Consumer<String> infoLog;
why not just pass on the logger itself?

2025-03-21 14:59 UTC, davidmayr commented on api/src/main/java/com/infernalsuite/aswm/api/world/ActiveSlimeWorld.java
> +    SlimeWorld getSnapshot();
clone method?

2025-04-03 06:23 UTC, CarmJos commented
I'm now developing a system for minigames & creative areas for other developers & players, and petty requiring interfaces like this.

 (Currently I'm using jar dependency to using serialization & deserializations, which is not elegant at all.)

So, looking forward to see this pr to be merged.

2025-04-03 06:26 UTC, davidmayr commented
> I'm now developing a system for minigames & creative areas for other developers & players, and petty requiring interfaces like this.
> 
> (Currently I'm using jar dependency to using serialization & deserializations, which is not elegant at all.)
> 
> So, looking forward to see this pr to be merged.

I think this PR is dead. I will try to implement this for the 1.21.5 release if I find the time to do so. If you want, you can also re-do this PR on the current "develop" branch with the changes I suggested, and we may be able to get this done faster

2025-04-03 06:36 UTC, CarmJos commented
> > I'm now developing a system for minigames & creative areas for other developers & players, and petty requiring interfaces like this.
> > (Currently I'm using jar dependency to using serialization & deserializations, which is not elegant at all.)
> > So, looking forward to see this pr to be merged.
> 
> I think this PR is dead. I will try to implement this for the 1.21.5 release if I find the time to do so. If you want, you can also re-do this PR on the current "develop" branch with the changes I suggested, and we may be able to get this done faster

Yeah I noticed that this pr first created in 2023, 2 yeasrs ago..

If so, I gonna redesign those new interfaces, and create a new pr for this in those days.

2025-04-10 22:00 UTC, Unoqwy commented
> I think this PR is dead

Yeah I haven't used this in a couple years and forgot all about it. I'll leave the PR open so you can close it when you have a new one to replace it

2025-04-20 15:29 UTC, davidmayr commented
This was restructured and implemented into API 4.0. Thanks for your contribution.

2025-04-20 15:29 UTC, closed without merging