v12 SRF (per-chunk PDC support, no double-compression); fix bad bug causing chunks go poof.
InfernalSuite/AdvancedSlimePaper pull request #91
Opened 2023-12-19 20:57 UTC by kyngs

This PR attempts to add per-chunk PDC support.
To test this functionality, one can use the plugin I've coded for this https://github.com/kyngs/ASP-PDCTest/tree/pr90

@ComputerNerd100 raised concerns about how I wrap NMSChunk around the original SlimeChunk, so please review that.
This is a bigger PR, so there may be some bugs, I've done a lot of testing tho.

*Hopefully I didn't forget anything.*

2023-12-22 13:28 UTC, MenschenToaster commented
Could Issue #5 be implemented with the custom chunk compound tags as well? 🤔

2023-12-22 16:08 UTC, FabulousCodingFox commented
In the current implementation, your patch 0011 clashes with the already existing patch 0011-Make-SlimeWorld-a-PersistentDataHolder in the 1.20.4 version

2023-12-22 16:10 UTC, kyngs commented
> In the current implementation, your patch 0011 clashes with the already existing patch 0011-Make-SlimeWorld-a-PersistentDataHolder in the 1.20.4 version

hm, that one ain't from 1.20.4, but from main. Gonna do a quick rebase!

2023-12-22 16:14 UTC, kyngs commented
Done, thanks for the tip

2023-12-30 13:32 UTC, Paul19988 requested changes

2023-12-30 13:32 UTC, Paul19988 commented on core/src/main/java/com/infernalsuite/aswm/serialization/anvil/AnvilWorldReader.java
> +        var extraTag = new CompoundTag("", new CompoundMap());
Change this usage of var to a proper reference

2023-12-30 13:32 UTC, Paul19988 commented on core/src/main/java/com/infernalsuite/aswm/serialization/anvil/AnvilWorldReader.java
> +        extraTag.getValue().put(compound.getValue().get("ChunkBukkitValues")); // An attempt to migrate PDC from the anvil to the slime format.
```suggestion
        extraTag.getValue().put(compound.getValue().get("ChunkBukkitValues")); // Attempt to Migrate PDC from Anvil format to Slime format.
```

2023-12-30 13:32 UTC, Paul19988 commented on core/src/main/java/com/infernalsuite/aswm/serialization/slime/SlimeSerializer.java
> +                    System.err.println("Chunk at " + chunk.getX() + ", " + chunk.getZ() + " from world " + world.getName() + " has no extra data! When deserialized, this chunk will have an empty extr
Should use logger here

2023-12-30 13:32 UTC, Paul19988 commented on core/src/main/java/com/infernalsuite/aswm/serialization/slime/reader/impl/v12/v12SlimeWorldDeSerializer.java
> +            var extra = readCompound(rawExtra);
Remove usage of var

2023-12-30 13:32 UTC, Paul19988 commented on core/src/main/java/com/infernalsuite/aswm/serialization/slime/reader/impl/v12/v12SlimeWorldDeSerializer.java
> +            if (extra == null) extra = new CompoundTag("", new CompoundMap());
Can you wrap this in brackets for readability

2023-12-30 13:32 UTC, Paul19988 commented on core/src/main/java/com/infernalsuite/aswm/serialization/slime/reader/impl/v12/v12SlimeWorldDeSerializer.java
> +        if (tagBytes.length == 0) return null;
Can you wrap this in brackets for readability

2023-12-30 13:32 UTC, Paul19988 commented on patches/server/0012-Add-v12-chunk-pdc-and-extra-nbt.-Fix-double-compress.patch
> ++            //Bukkit.getLogger().log(Level.INFO, "CONVERTING NMS -> SKELETON");
If we're going to comment this out, we should remove it

2023-12-30 13:32 UTC, Paul19988 commented on patches/server/0012-Add-v12-chunk-pdc-and-extra-nbt.-Fix-double-compress.patch
> ++            //Bukkit.getLogger().log(Level.INFO, "CONVERTED TO SKELETON, PUSHING OFF-THREAD");
If we're going to comment this out, we should remove it

2023-12-30 13:57 UTC, Paul19988 approved these changes

2023-12-30 14:00 UTC, ComputerNerd100 commented
@Paul19988 @kyngs Ty for the var changes
Almost happy with this my end too
I'll update this to target develop shortly and then merge to there and we can get some snapshot releases out

2023-12-30 20:49 UTC, ComputerNerd100 approved these changes

2023-12-30 20:50 UTC, merged